name: Deploy Static Website

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Grant write access to repository contents (needed for pushing)

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Correctly use the GITHUB_TOKEN
          publish_dir: ./output  # The directory to publish from
          publish_branch: gh-pages  # The branch to publish to
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          commit_message: 'Deploy static site to GitHub Pages'
